name: PR Comment

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

permissions:
  actions: read
  issues: write
  checks: read
  statuses: read
  pull-requests: write

jobs:
  test:
    uses: bgd-labs/github-workflows/.github/workflows/comment.yml@main
    secrets: inherit
